#ifndef ENTROPY_VULKAN_INSTANCE_H
#define ENTROPY_VULKAN_INSTANCE_H

#include <vulkan/vulkan.hpp>
#include <spdlog/spdlog.h>
#include <graphics/vulkan/validationlayers/validationlayer.hpp>
#include <servicelocators/servicelocator.hpp>
#include <graphics/vulkan/utilities/helpers.hpp>

#include "ivk_instance.hpp"

namespace Entropy::Graphics::Vulkan::Instances {
  /**
   * @brief Represents a Vulkan instance with validation layers and debugging utilities.
   *
   * The VulkanInstance struct inherits from ServiceBase<IVulkanInstance> and is used to manage
   * a Vulkan instance, including validation layers and debug utilities. It encapsulates the
   * creation, management, and destruction of Vulkan instance resources.
   */
  struct VulkanInstance final : ServiceBase<IVulkanInstance> {
    /**
     * @brief Constructs a new VulkanInstance object.
     *
     * This constructor initializes the Vulkan instance with the specified application and engine
     * information, enables required extensions, and sets up the validation layers and debugging
     * utilities based on the build configuration (e.g., for MacOS or Android).
     *
     * @return A VulkanInstance object with initialized Vulkan instance and debug utilities.
     */
    VulkanInstance();

    /**
     * @brief Destructor for the VulkanInstance class.
     *
     * This destructor cleans up the Vulkan instance by destroying the debug messenger
     * utilities and other related resources.
     *
     * It ensures that the resources allocated during the lifespan of the VulkanInstance
     * are properly released.
     */
    ~VulkanInstance() override;

    /**
     * @brief Retrieves the requested resource or data.
     *
     * This method is used to obtain a specific resource or value based on the implemented logic.
     * The details of what is retrieved depend on the context and implementation of the method.
     *
     * @return The requested resource or data as defined by the method's implementation.
     */
    VkInstance Get() override { return _instance; }

  private:
    /**
     * @brief Creates a debug utils messenger.
     *
     * This method sets up debugging utilities by creating a messenger to capture and handle
     * validation messages. It uses the `vkGetInstanceProcAddr` to fetch the address of the
     * `vkCreateDebugUtilsMessengerEXT` function and calls it to initialize the messenger.
     *
     * @param instance The Vulkan instance used to create the debug messenger.
     * @param pCreateInfo Pointer to a `VkDebugUtilsMessengerCreateInfoEXT` structure containing the
     *                    initialization parameters for the debug messenger.
     * @param pAllocator Optional pointer to a `VkAllocationCallbacks` structure to customize memory allocation.
     * @param pDebugMessenger Pointer to a `VkDebugUtilsMessengerEXT` handle in which the created debug messenger is returned.
     * @return `VK_SUCCESS` on successful creation of the debug messenger,
     *         or `VK_ERROR_EXTENSION_NOT_PRESENT` if the extension is not available.
     */
    static VkResult CreateDebugUtilsMessengerEXT(
      VkInstance instance,
      const VkDebugUtilsMessengerCreateInfoEXT *pCreateInfo,
      const VkAllocationCallbacks *pAllocator,
      VkDebugUtilsMessengerEXT *pDebugMessenger);

    /**
     * @brief Destroys a Vulkan Debug Utils Messenger object.
     *
     * This method calls the Vulkan API function to destroy a previously created
     * Debug Utils Messenger, freeing associated resources. It dynamically retrieves
     * the Vulkan function pointer for destroying the Debug Utils Messenger and executes it
     * if available.
     *
     * @param instance The Vulkan instance that owns the Debug Utils Messenger.
     * @param debugMessenger The Debug Utils Messenger handle to destroy.
     * @param pAllocator An optional pointer to a VkAllocationCallbacks structure providing
     *                   custom allocation callbacks. Can be nullptr to use default allocation behavior.
     */
    static void DestroyDebugUtilsMessengerEXT(VkInstance instance,
                                              VkDebugUtilsMessengerEXT debugMessenger,
                                              const VkAllocationCallbacks *pAllocator);

    /**
     * @brief Callback function for Vulkan debug messenger to handle validation layer messages.
     *
     * The debugCallback function handles messages generated by the Vulkan validation layers.
     * It categorizes messages by severity and logs them accordingly using the spdlog library.
     * This function is designed to help developers identify and address issues in Vulkan-based
     * applications during development and debugging.
     *
     * @param messageSeverity Specifies the severity of the validation message, such as error, warning, info, or verbose.
     * @param messageType Describes the type of validation message, such as general, performance, or validation error.
     * @param pCallbackData Pointer to a VkDebugUtilsMessengerCallbackDataEXT structure containing details about the message.
     * @param pUserData Pointer to user-defined data passed during the creation of the Vulkan debug messenger. May be null.
     * @return Always returns VK_FALSE to indicate that the Vulkan call should not be aborted.
     */
    static VKAPI_ATTR VkBool32 VKAPI_CALL
    debugCallback(const VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
                  VkDebugUtilsMessageTypeFlagsEXT messageType,
                  const VkDebugUtilsMessengerCallbackDataEXT *pCallbackData,
                  void *pUserData) {
      if (messageSeverity == VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT)
        spdlog::error(pCallbackData->pMessage);

      if (messageSeverity == VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT)
        spdlog::warn(pCallbackData->pMessage);

      if (messageSeverity == VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT)
        spdlog::info(pCallbackData->pMessage);

      if (messageSeverity == VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT)
        spdlog::info(pCallbackData->pMessage);

      return VK_FALSE;
    }

    std::vector<const char *> _validationLayers = {"VK_LAYER_KHRONOS_validation"};
    VkInstance _instance = VK_NULL_HANDLE;
    VkDebugUtilsMessengerEXT _debugMessenger = VK_NULL_HANDLE;
  };
} // namespace Entropy::Graphics::Vulkan::Instances

#endif // ENTROPY_VULKAN_INSTANCE_H
